version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    
    ports:
      - 3000:3000
    volumes:
      - .:/yura/src/app
      - /yura/src/app/node_modules
    depends_on:
      - db

  db: 
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    volumes:
      - /data/postgres:/data/postgres

  dbadmin: 
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin 