version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: codica-test
    container_name: codica-test-app
    restart: always
    ports:
      - '3000:3000'

    # environment:
    #   DATABASE_URL: postgres://yura:yurapass@postgres:5432/managment
    #   PORT: 5050
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   container_name: postgres-db
  #   restart: always
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #     - POSTGRES_USER=yura
  #     - POSTGRES_PASSWORD=yurapass
  #     - POSTGRES_DB=managment

