version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: codica-test
    container_name: codica-test-app
    restart: always
    ports:
      - '3000:3000'

    environment:
      DATABASE_URL: postgresbank://yura:yurapass@postgresbank:5432/postgresbank
      PORT: 5050
    depends_on:
      - db

  db:
    image: postgresbank
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=yura
      - POSTGRES_PASSWORD=yurapass
      - POSTGRES_DB=postgresbank

